name: Commit Count Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Conform Action
      uses: talos-systems/conform@v0.1.0-alpha.19
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
